name = "morning-credit-8a59"
main = "worker.js"
compatibility_date = "2026-06-05"
workers_dev = true

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "e69428e3-6524-427c-bae3-d32190e5c229"

[vars]
COMPANY_NAME = "Prumo Sistemas"
COOKIE_MODE = "prod"
FRONTEND_ORIGINS = "https://app.prumosistemas.com.br"
PYTHON_API_URL = "https://api.prumosistemas.com.br"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
head_sampling_rate = 0.25
